name: zentri

services:
  postgres:
    image: postgres:16-alpine
    container_name: zentri-postgres
    environment:
      POSTGRES_DB: zentri_dev
      POSTGRES_USER: zentri
      POSTGRES_PASSWORD: zentri
    ports:
      - "5433:5432"
    volumes:
      - zentri_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zentri -d zentri_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - zentri-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: zentri-mailpit
    environment:
      MP_UI_AUTH: ${MAILPIT_AUTH:-}     
      MP_MAX_MESSAGES: ${MAILPIT_MAX_MESSAGES:-500}
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
      - "${MAILPIT_UI_PORT:-8025}:8025"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8025/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - zentri-network

  minio:
    image: minio/minio:latest
    container_name: zentri-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-zentri}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-zentri-secret}

      MINIO_BROWSER_REDIRECT_URL: ${MINIO_CONSOLE_URL:-http://localhost:9001}
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - zentri_minio_data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:9000/minio/health/live >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - zentri-network

volumes:
  zentri_postgres_data:
  zentri_minio_data:

networks:
  zentri-network:
    driver: bridge
