name: CI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - ".vscode/**"
      - ".idea/**"

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CI: "true"
  NEXT_TELEMETRY_DISABLED: "1"
  DATABASE_URL: "postgres://postgres:postgres@localhost:5432/app"

jobs:
  build_and_lint:
    name: Build & Lint (Biome CI)
    runs-on: ubuntu-latest
    timeout-minutes: 25

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: app
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d app"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack & pin pnpm@10.15.1
        run: |
          corepack enable
          corepack prepare pnpm@10.15.1 --activate
          pnpm -v
          node -v

      - name: Setup Node (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify lockfile consistency
        run: |
          git diff --exit-code --quiet -- pnpm-lock.yaml || (
            echo "Lockfile drift detected. Commit pnpm-lock.yaml changes."
            git --no-pager diff -- pnpm-lock.yaml
            exit 1
          )

      - name: Validate Drizzle migrations
        working-directory: packages/db
        run: pnpm drizzle-kit check

      - name: Build
        run: pnpm build

      - name: Lint (Biome CI)
        run: pnpm lint:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: pnpm test
