name: Deploy to AWS

on:
  push:
    branches: [main]

env:
  CI: true
  AWS_REGION: "af-south-1"
  STAGE: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

jobs:
  deployment:
    name: Deploy App
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment:
      name: ${{ github.ref_name == 'main' && 'prod' || 'preview' }}
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false

      - name: Restore Turbo cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-node20-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-node20-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.ref_name }}-
            turbo-${{ runner.os }}-node20-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Validate stage
        run: |
          if [ -z "${{ env.STAGE }}" ] || [ "${{ env.STAGE }}" = "false" ]; then
            echo "STAGE is not set correctly"; exit 1;
          fi

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-action-zentri-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy
        run: pnpm exec sst deploy --stage=${{ env.STAGE }}
